import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 — Cream/Lime palette
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#141f00",
        primary: "#4b6700",
        "surface-container-high": "#eee9cc",
        "on-primary-container": "#4f6d00",
        "on-error-container": "#93000a",
        "primary-container": "#b6f500",
        "inverse-on-surface": "#f6f2d4",
        "on-surface": "#1d1c0a",
        "surface-dim": "#dfdbbe",
        "inverse-surface": "#33311d",
        "on-tertiary-container": "#4f6d00",
        "on-surface-variant": "#434933",
        "primary-fixed": "#b7f605",
        "surface-tint": "#4b6700",
        "on-secondary": "#ffffff",
        "tertiary-container": "#bbf33a",
        "on-error": "#ffffff",
        tertiary: "#4b6700",
        background: "#fffade",
        "tertiary-fixed-dim": "#a2d818",
        error: "#ba1a1a",
        "surface-container": "#f3efd1",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#bbf62d",
        "on-tertiary-fixed": "#141f00",
        "surface-variant": "#e8e3c6",
        "tertiary-fixed": "#bdf53c",
        "outline-variant": "#c3caad",
        "surface-container-low": "#f9f4d7",
        "surface-container-highest": "#e8e3c6",
        "secondary-fixed-dim": "#a0d800",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#141f00",
        "on-primary-fixed-variant": "#384e00",
        surface: "#fffade",
        "on-secondary-fixed-variant": "#384e00",
        outline: "#737a61",
        "surface-bright": "#fffade",
        "primary-fixed-dim": "#a0d800",
        secondary: "#4b6700",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#a0d800",
        "on-secondary-container": "#506e00",
        "secondary-container": "#bbf62d",
        "on-tertiary-fixed-variant": "#384e00",
        "on-background": "#1d1c0a",
        // Lime accent
        lime: "#B6F500",
      },
      fontFamily: {
        sans: ["Epilogue", "system-ui", "sans-serif"],
        epilogue: ["Epilogue", "system-ui", "sans-serif"],
        "body-md": ["Epilogue"],
        "display-lg": ["Epilogue"],
        "headline-lg": ["Epilogue"],
        "headline-sm": ["Epilogue"],
        "display-md": ["Epilogue"],
        "body-lg": ["Epilogue"],
        "label-caps": ["Epilogue"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "display-md": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      boxShadow: {
        card: "0 2px 12px rgba(75,103,0,0.07), 0 1px 3px rgba(75,103,0,0.04)",
        "card-hover": "0 6px 24px rgba(75,103,0,0.12)",
        lime: "0 4px 16px rgba(182,245,0,0.35)",
      },
      backgroundImage: {
        mesh: "radial-gradient(at 0% 0%, rgba(182,245,0,0.10) 0px, transparent 50%), radial-gradient(at 100% 100%, rgba(182,245,0,0.05) 0px, transparent 50%)",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4,0,0.6,1) infinite",
        "bar-grow": "barGrow 0.8s cubic-bezier(0.4,0,0.2,1) forwards",
        "ring-progress": "ringProgress 1.4s cubic-bezier(0.4,0,0.2,1) forwards",
      },
    },
  },
  plugins: [],
} satisfies Config;
